language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3.5"
cache: pip
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > tests/cc-test-reporter
  - chmod +x tests/cc-test-reporter
  - tests/cc-test-reporter before-build
install:
  - pip install -r requirements.txt
  - pip install coverage
script:
  - cd tests
  - export PYTHONPATH=..
  - cp ../.coveragerc ../*.cfg .
  - coverage run manage.py test
  - coverage xml
  - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT

